#!/bin/sh                                      
                                                     
# Start all init scripts in /etc/rcS.d and /etc/rc5.d
# executing them in numerical order.        

/opt/smartlocker/face_loop.sh   

echo 77 > /sys/class/gpio/export
cd /sys/class/gpio/gpio77
echo out > direction
echo 1 > value
cd ~

/opt/smartlocker/face_recg.sh          
                                            
for i in /etc/rcS.d/S??* /etc/rc5.d/S??* ;do
                                         
     # Ignore dangling symlinks (if any).   
     [ ! -f "$i" ] && continue              
                                            
     case "$i" in                           
        *.sh)                               
            # Source shell script for speed.
            (                       
                trap - INT QUIT TSTP
                set start                         
                . $i                              
            )                                     
            ;;                                    
        *)
            # No sh extension, so fork subprocess.
            $i start                              
            ;;                                    
    esac                                          
done  
